defaults:
  - _self_

method: n-cps

train:
  total_epochs: 150
  validation_interval: 10

init:
  _target_: trainer.NCPSTrainer

  num_models: 4

  supervised_criterion:
    _target_: torch.nn.MSELoss

  unsupervised_criterion:
    _target_: torch.nn.MSELoss

  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 0.005
    weight_decay: 0.001

  scheduler:
    _target_: torch.optim.lr_scheduler.StepLR
    _partial_: true
    step_size: 1
    gamma: 0.99

  cps_weight: 0.05
  cps_rampup_epochs: 20
