defaults:
  - _self_

name: HC gcn ensemble 

num_node_features: 11
hidden_channels: 128
num_layers: 3
dropout: 0.2

init:
  _target_: models.GCN
  _partial_: false
  num_node_features: ${model.num_node_features}
  hidden_channels: ${model.hidden_channels}
  num_layers: ${model.num_layers}
  dropout: ${model.dropout}
